# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vs57brUVUiiqNCQdD1d6zOdVOwnk9wFf
"""

def combine(arr1, arr2):
    ans = []
    i, j = 0, 0
    n1, n2 = len(arr1), len(arr2)
    for _ in range(n1 + n2):
        if i < n1 and (j >= n2 or arr1[i] <= arr2[j]):
            ans.append(arr1[i])
            i += 1
        elif j < n2:
            ans.append(arr2[j])
            j += 1
    return ans

def main():
    n1 = int(input())
    arr1 = list(map(int, input().split()))
    n2 = int(input())
    if n2 > 0:
        arr2 = list(map(int, input().split()))
    else:
        arr2 = []

    merged = combine(arr1, arr2)
    print(*merged)

main()

